name: Publish Release

on:
  release:
    types: [published]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Set root branch
        run: echo RELEASE_BRANCH=release/$(echo ${{ github.event.release.name }} | sed -e 's/^\(.\{4\}\).*$/\1/') >> $GITHUB_ENV


      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          fetch-depth: 0

      - name: Fetch older tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Install Packages
        run: yarn install

      - name: Build
        run: yarn start build

      - name: Bump new release version
        run: |
          HUSKY=0 yarn start version.graduate
          yarn install
          git add .
          HUSKY=0 git commit --amend --no-edit
          git push origin ${{ env.RELEASE_BRANCH }} --tags

      - name: Authenticate
        run: |
          echo "@grandcore:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: lerna publish from-package --no-verify-access --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
