name: Release

on:
  pull_request:
    branches:
      - main

jobs:
  create-version:
    name: Bump new version
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: start version.${{ env.RELEASE }}

